# Generated by Django 5.2.1 on 2025-05-30 17:06

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyLearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.contentstandard')),
            ],
            options={
                'unique_together': {('standard', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.classlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.classlevel')),
            ],
            options={
                'unique_together': {('class_level', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SubStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.strand')),
            ],
        ),
        migrations.AddField(
            model_name='contentstandard',
            name='substrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.substrand'),
        ),
        migrations.CreateModel(
            name='Tlr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('brief_description', models.TextField()),
                ('time_needed', models.CharField(choices=[('quick', '5-10 min'), ('lesson', '30-40 min'), ('reusable', 'Reusable / multi-use')], default='lesson', max_length=10)),
                ('steps_to_make', models.TextField(blank=True)),
                ('tips_for_use', models.TextField(blank=True)),
                ('intended_use', models.CharField(blank=True, choices=[('intro', 'Introduction'), ('aid', 'Teaching Aid'), ('assessment', 'Assessment')], max_length=20, null=True)),
                ('tlr_type', models.CharField(blank=True, max_length=20, null=True)),
                ('learning_difficulty', models.CharField(blank=True, choices=[('none', 'None'), ('dyslexia', 'Dyslexia'), ('adhd', 'ADHD'), ('visual', 'Visual Impairment'), ('hearing', 'Hearing Impairment'), ('autism', 'Autism Spectrum'), ('other', 'Other')], default='none', max_length=20, null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.classlevel')),
                ('competencies', models.ManyToManyField(blank=True, to='suggestor.corecompetency')),
                ('goals', models.ManyToManyField(blank=True, to='suggestor.goaltag')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.indicator')),
                ('key_learning_areas', models.ManyToManyField(blank=True, to='suggestor.keylearningarea')),
                ('materials', models.ManyToManyField(blank=True, to='suggestor.material')),
                ('resource_types', models.ManyToManyField(blank=True, to='suggestor.resourcetype')),
                ('strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.strand')),
                ('subject', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='class_level', chained_model_field='class_level', null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.subject')),
                ('substrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.substrand')),
                ('themes', models.ManyToManyField(blank=True, to='suggestor.theme')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contentstandard',
            unique_together={('substrand', 'code')},
        ),
    ]
