# Generated by Django 5.2.1 on 2025-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tlr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=120)),
                ('sub_strand', models.CharField(blank=True, max_length=120)),
                ('class_level', models.CharField(choices=[('KG', 'KG'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3')], max_length=3)),
                ('intended_use', models.CharField(choices=[('intro', 'Introduction'), ('aid', 'Teaching Aid'), ('assessment', 'Assessment')], max_length=12)),
                ('tlr_type', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('brief_description', models.TextField()),
                ('time_needed', models.CharField(choices=[('quick', '5-10 min'), ('lesson', '30-40 min'), ('reusable', 'Reusable / multi-use')], default='lesson', max_length=10)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('classroom_setup', models.CharField(blank=True, max_length=120)),
                ('steps_to_make', models.TextField()),
                ('tips_for_use', models.TextField(blank=True)),
                ('materials', models.ManyToManyField(blank=True, to='suggestor.material')),
            ],
        ),
    ]
