# Generated by Django 5.2.1 on 2025-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strand',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], default=1),
            preserve_default=False,
        ),
    ]
