# Generated by Django 5.2.1 on 2025-05-29 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestor', '0002_classlevel_strand_substrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyLearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tlr',
            name='accessibility_notes',
        ),
        migrations.RemoveField(
            model_name='tlr',
            name='classroom_setup',
        ),
        migrations.RemoveField(
            model_name='tlr',
            name='sub_strand',
        ),
        migrations.AddField(
            model_name='tlr',
            name='substrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.substrand'),
        ),
        migrations.AddField(
            model_name='tlr',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tlr',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.classlevel'),
        ),
        migrations.AlterField(
            model_name='tlr',
            name='intended_use',
            field=models.CharField(blank=True, choices=[('intro', 'Introduction'), ('aid', 'Teaching Aid'), ('assessment', 'Assessment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tlr',
            name='steps_to_make',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tlr',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.strand'),
        ),
        migrations.AlterField(
            model_name='tlr',
            name='tlr_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ContentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('substrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.substrand')),
            ],
            options={
                'unique_together': {('substrand', 'code')},
            },
        ),
        migrations.AddField(
            model_name='tlr',
            name='competencies',
            field=models.ManyToManyField(blank=True, to='suggestor.corecompetency'),
        ),
        migrations.AddField(
            model_name='tlr',
            name='goals',
            field=models.ManyToManyField(blank=True, to='suggestor.goaltag'),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.contentstandard')),
            ],
            options={
                'unique_together': {('standard', 'code')},
            },
        ),
        migrations.AddField(
            model_name='tlr',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.indicator'),
        ),
        migrations.AddField(
            model_name='tlr',
            name='key_learning_areas',
            field=models.ManyToManyField(blank=True, to='suggestor.keylearningarea'),
        ),
        migrations.AddField(
            model_name='tlr',
            name='resource_types',
            field=models.ManyToManyField(blank=True, to='suggestor.resourcetype'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestor.classlevel')),
            ],
            options={
                'unique_together': {('class_level', 'title')},
            },
        ),
        migrations.AddField(
            model_name='tlr',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.subject'),
        ),
        migrations.AddField(
            model_name='tlr',
            name='themes',
            field=models.ManyToManyField(blank=True, to='suggestor.theme'),
        ),
    ]
