# Generated by Django 5.2.1 on 2025-06-01 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestor', '0002_strand_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='strand',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestor.subject'),
        ),
    ]
