# Generated by Django 5.2.1 on 2025-06-29 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestor', '0002_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='element_clicked',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='error_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='filters_applied',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='referrer',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='request_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='response_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='route_selected',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='scroll_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='search_results_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='session_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='time_on_page',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', '🔑 Login'), ('logout', '🔒 Logout'), ('page_view', '👁️ Page View'), ('view_tlr', '📖 Viewed TLR'), ('download_tlr', '⬇️ Downloaded TLR'), ('search', '🔍 Performed Search'), ('filter_applied', '🎛️ Applied Filters'), ('route_selected', '🛤️ Selected Search Route'), ('form_submitted', '📝 Submitted Form'), ('button_click', '🖱️ Button Click'), ('link_click', '🔗 Link Click'), ('error_encountered', '❌ Error Encountered'), ('session_start', '🚀 Session Started'), ('session_end', '🏁 Session Ended')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'timestamp'], name='suggestor_u_user_id_595940_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action', 'timestamp'], name='suggestor_u_action_98102d_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id'], name='suggestor_u_session_4ddb68_idx'),
        ),
    ]
