# Generated by Django 5.2.1 on 2025-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestor', '0003_useractivity_browser_useractivity_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlr',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
